### ISSUE TITLE
Look into using proxies for patching

### ISSUE THREAD

**Issue by btford** [angular/dom-interceptor#3]
via https://github.com/ealtenho/controller-training/issues/23

https://github.com/tvcutsem/harmony-reflect

**Comment by ealtenho** [comment]
@btford 
Okay, I started looking into this before seeing the issue here and the link. Due to that, I started with a naive implementation of making my own proxies: https://github.com/angular/dom-interceptor/commit/18581f65fa835fb760109e65b24c7cbd8024d270 specifically, https://github.com/angular/dom-interceptor/blob/master/dom-interceptor.js#L347-L435

Is this getting somewhere?

**Comment by btford** [comment]
Why not use https://github.com/tvcutsem/harmony-reflect directly? This would make implementing this lib much simpler.

**Comment by ealtenho** [comment]
Okay. I will look into it. Thanks!

**Comment by ealtenho** [comment]
I've patched basic accessor methods like `document.getElementById` so that they will return proxies. I think I should also patch `document.create` to return proxies and possibly `document.body`. I'm not sure if there is a better way than patching some of these properties individually, as patching `document.prototype` as a whole would not catch `document.body`, and some of the accessor methods return groups of items versus single items. After expanding the list, I will have to change `addManipulationListener` to use `patchAccess` rather than `patchExistingElements`.

**Comment by ealtenho** [comment]
Okay, tying together this issue and #4, that proxies are not yet fully functional in current browsers, I will leave the proxy methods in DOM-Interceptor as functions that might be useful for patching, but I will leave our add/remove methods to depend on the patching methods that work in current browsers.

**Comment by ealtenho** [comment]
https://github.com/angular/dom-interceptor/commit/160b703038bc90cb0fc1813b759cd585aa47a257

**Comment by ealtenho** [comment]
Since proxies are not yet fully supported in browsers, we've decided to rely on different strategies. See #4 #6
